### ISSUE TITLE
Make a 1.0.0 release?

### ISSUE THREAD

**Issue by bastelfreak** [glennsarti/puppetfile-resolver#18]
Hi @glennsarti !
I'm currently digging through all the puppet-bolt dependencies to package them properly for Arch Linux / internally for $company. Many orgs/enterprises have a requirement to install only stable software / software with a stable API. I assume puppetfile-resolver follows semantic versioning and it's also a dependency of bolt. Any chance to publish a 1.0.0 release soonish?

**Comment by glennsarti** [comment]
Hi @bastelfreak , honestly the API isn't stable enough for a 1.0 yet.  I will release it as 1.0 once I feel its ready.
